services:
  mongo:
    image: ghcr.io/tapdata/tapdata:latest
    container_name: tapdata-mongo-official
    # Create directories before starting mongod
    command: 
      - sh
      - -c
      - |
        mkdir -p /tapdata/data/logs /tapdata/data/db
        mongod --dbpath=/tapdata/data/db/ --replSet=rs0 --bind_ip_all --logpath=/tapdata/data/logs/mongod.log
    environment:
      - dbMem=1
    volumes:
      - ./data/db:/tapdata/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "rs.initiate()"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - tapdata-net

  tm:
    image: ghcr.io/tapdata/tapdata:latest
    container_name: tapdata-tm-official
    working_dir: /tapdata/apps
    # Run only TM Jar
    command: ["java", "-Xmx2g", "-jar", "-Dserver.port=3030", "-server", "components/tm.jar", "--spring.config.additional-location=file:etc/", "--logging.config=file:etc/logback.xml", "--spring.data.mongodb.default.uri=mongodb://tapdata-mongo-official:27017/tapdata?replicaSet=rs0", "--spring.data.mongodb.obs.uri=mongodb://tapdata-mongo-official:27017/tapdata?replicaSet=rs0", "--spring.data.mongodb.log.uri=mongodb://tapdata-mongo-official:27017/tapdata?replicaSet=rs0"]
    depends_on:
      - mongo
    ports:
      - "3030:3030"
    environment:
      - managerMem=2g
      - tm_port=3030
      - MONGO_URI=mongodb://tapdata-mongo-official:27017/tapdata?replicaSet=rs0
    networks:
      - tapdata-net

  engine:
    image: ghcr.io/tapdata/tapdata:latest
    container_name: tapdata-engine-official
    working_dir: /tapdata/apps
    # Run only Engine Jar
    command: ["java", "-Xmx2g", "-jar", "components/tapdata-agent.jar"]
    depends_on:
      - tm
    environment:
      - app_type=DAAS
      - tm_port=3030
      - backend_url=http://tapdata-tm-official:3030/api/
      - MONGO_URI=mongodb://tapdata-mongo-official:27017/tapdata?replicaSet=rs0
      - TAPDATA_MONGO_URI=mongodb://tapdata-mongo-official:27017/tapdata?replicaSet=rs0
      - engineMem=2g
    networks:
      - tapdata-net

networks:
  tapdata-net:
    driver: bridge
