services:
  mongo:
    image: ghcr.io/tapdata/tapdata:latest
    container_name: tapdata-mongo-official
    # Create directories before starting mongod
    command: 
      - sh
      - -c
      - |
        tr -d '\r' < /tapdata/scripts/start_mongo.sh > /tmp/start_mongo.sh
        chmod +x /tmp/start_mongo.sh
        /tmp/start_mongo.sh
    environment:
      - dbMem=2
    volumes:
      - ./data/db:/tapdata/data/db
      - ./scripts:/tapdata/scripts
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "rs.status().ok || rs.initiate()"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - tapdata-net

  tm:
    image: ghcr.io/tapdata/tapdata:latest
    container_name: tapdata-tm-official
    working_dir: /tapdata/apps
    # Run only TM Jar
    command: 
      - sh
      - -c
      - |
        tr -d '\r' < /tapdata/scripts/start_tm.sh > /tmp/start_tm.sh
        chmod +x /tmp/start_tm.sh
        /tmp/start_tm.sh
    depends_on:
      - mongo
    ports:
      - "8080:3030"
    environment:
      - managerMem=4g
      - tm_port=3030
      - MONGO_URI=mongodb://tapdata-mongo-official:27017/tapdata?replicaSet=rs0
    volumes:
      - ./scripts:/tapdata/scripts
    networks:
      - tapdata-net

  engine:
    image: ghcr.io/tapdata/tapdata:latest
    container_name: tapdata-engine-official
    working_dir: /tapdata/apps
    # Run only Engine Jar
    command: ["java", "-Xms4g", "-Xmx4g", "-jar", "components/tapdata-agent.jar"]
    depends_on:
      - tm
    environment:
      - app_type=DAAS
      - tm_port=3030
      - backend_url=http://tapdata-tm-official:3030/api/
      - MONGO_URI=mongodb://tapdata-mongo-official:27017/tapdata?replicaSet=rs0
      - TAPDATA_MONGO_URI=mongodb://tapdata-mongo-official:27017/tapdata?replicaSet=rs0
      - engineMem=4g
    networks:
      - tapdata-net

networks:
  tapdata-net:
    driver: bridge