package com.tapdata.processor.dataflow.pb.ca;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlatformLogout.proto

public final class PlatformLogout {
  private PlatformLogout() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UnitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Unit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Unit.Logout logout = 1;</code>
     * @return Whether the logout field is set.
     */
    boolean hasLogout();
    /**
     * <code>.Unit.Logout logout = 1;</code>
     * @return The logout.
     */
    Unit.Logout getLogout();
    /**
     * <code>.Unit.Logout logout = 1;</code>
     */
    Unit.LogoutOrBuilder getLogoutOrBuilder();
  }
  /**
   * Protobuf type {@code Unit}
   */
  public static final class Unit extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Unit)
      UnitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Unit.newBuilder() to construct.
    private Unit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Unit() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Unit();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Unit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Logout.Builder subBuilder = null;
              if (logout_ != null) {
                subBuilder = logout_.toBuilder();
              }
              logout_ = input.readMessage(Logout.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(logout_);
                logout_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlatformLogout.internal_static_Unit_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlatformLogout.internal_static_Unit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Unit.class, Builder.class);
    }

    public interface LogoutOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Unit.Logout)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *登出时间
       * </pre>
       *
       * <code>string logoutTime = 1;</code>
       * @return The logoutTime.
       */
      String getLogoutTime();
      /**
       * <pre>
       *登出时间
       * </pre>
       *
       * <code>string logoutTime = 1;</code>
       * @return The bytes for logoutTime.
       */
      com.google.protobuf.ByteString
          getLogoutTimeBytes();

      /**
       * <pre>
       *登出流水号
       * </pre>
       *
       * <code>string loginoutNumber = 2;</code>
       * @return The loginoutNumber.
       */
      String getLoginoutNumber();
      /**
       * <pre>
       *登出流水号
       * </pre>
       *
       * <code>string loginoutNumber = 2;</code>
       * @return The bytes for loginoutNumber.
       */
      com.google.protobuf.ByteString
          getLoginoutNumberBytes();
    }
    /**
     * Protobuf type {@code Unit.Logout}
     */
    public static final class Logout extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Unit.Logout)
        LogoutOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Logout.newBuilder() to construct.
      private Logout(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Logout() {
        logoutTime_ = "";
        loginoutNumber_ = "";
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new Logout();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Logout(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                String s = input.readStringRequireUtf8();

                logoutTime_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                loginoutNumber_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlatformLogout.internal_static_Unit_Logout_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlatformLogout.internal_static_Unit_Logout_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Logout.class, Builder.class);
      }

      public static final int LOGOUTTIME_FIELD_NUMBER = 1;
      private volatile Object logoutTime_;
      /**
       * <pre>
       *登出时间
       * </pre>
       *
       * <code>string logoutTime = 1;</code>
       * @return The logoutTime.
       */
      @Override
      public String getLogoutTime() {
        Object ref = logoutTime_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          logoutTime_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *登出时间
       * </pre>
       *
       * <code>string logoutTime = 1;</code>
       * @return The bytes for logoutTime.
       */
      @Override
      public com.google.protobuf.ByteString
          getLogoutTimeBytes() {
        Object ref = logoutTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          logoutTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int LOGINOUTNUMBER_FIELD_NUMBER = 2;
      private volatile Object loginoutNumber_;
      /**
       * <pre>
       *登出流水号
       * </pre>
       *
       * <code>string loginoutNumber = 2;</code>
       * @return The loginoutNumber.
       */
      @Override
      public String getLoginoutNumber() {
        Object ref = loginoutNumber_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          loginoutNumber_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *登出流水号
       * </pre>
       *
       * <code>string loginoutNumber = 2;</code>
       * @return The bytes for loginoutNumber.
       */
      @Override
      public com.google.protobuf.ByteString
          getLoginoutNumberBytes() {
        Object ref = loginoutNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          loginoutNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getLogoutTimeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, logoutTime_);
        }
        if (!getLoginoutNumberBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loginoutNumber_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getLogoutTimeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, logoutTime_);
        }
        if (!getLoginoutNumberBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loginoutNumber_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Logout)) {
          return super.equals(obj);
        }
        Logout other = (Logout) obj;

        if (!getLogoutTime()
            .equals(other.getLogoutTime())) return false;
        if (!getLoginoutNumber()
            .equals(other.getLoginoutNumber())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + LOGOUTTIME_FIELD_NUMBER;
        hash = (53 * hash) + getLogoutTime().hashCode();
        hash = (37 * hash) + LOGINOUTNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getLoginoutNumber().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Logout parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Logout parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Logout parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Logout parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Logout parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Logout parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Logout parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Logout parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Logout parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Logout parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Logout parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Logout parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Logout prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Unit.Logout}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Unit.Logout)
          LogoutOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return PlatformLogout.internal_static_Unit_Logout_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return PlatformLogout.internal_static_Unit_Logout_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Logout.class, Builder.class);
        }

        // Construct using PlatformLogout.Unit.Logout.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          logoutTime_ = "";

          loginoutNumber_ = "";

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return PlatformLogout.internal_static_Unit_Logout_descriptor;
        }

        @Override
        public Logout getDefaultInstanceForType() {
          return Logout.getDefaultInstance();
        }

        @Override
        public Logout build() {
          Logout result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public Logout buildPartial() {
          Logout result = new Logout(this);
          result.logoutTime_ = logoutTime_;
          result.loginoutNumber_ = loginoutNumber_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Logout) {
            return mergeFrom((Logout)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Logout other) {
          if (other == Logout.getDefaultInstance()) return this;
          if (!other.getLogoutTime().isEmpty()) {
            logoutTime_ = other.logoutTime_;
            onChanged();
          }
          if (!other.getLoginoutNumber().isEmpty()) {
            loginoutNumber_ = other.loginoutNumber_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Logout parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Logout) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object logoutTime_ = "";
        /**
         * <pre>
         *登出时间
         * </pre>
         *
         * <code>string logoutTime = 1;</code>
         * @return The logoutTime.
         */
        public String getLogoutTime() {
          Object ref = logoutTime_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            logoutTime_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         *登出时间
         * </pre>
         *
         * <code>string logoutTime = 1;</code>
         * @return The bytes for logoutTime.
         */
        public com.google.protobuf.ByteString
            getLogoutTimeBytes() {
          Object ref = logoutTime_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            logoutTime_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *登出时间
         * </pre>
         *
         * <code>string logoutTime = 1;</code>
         * @param value The logoutTime to set.
         * @return This builder for chaining.
         */
        public Builder setLogoutTime(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          logoutTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *登出时间
         * </pre>
         *
         * <code>string logoutTime = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearLogoutTime() {

          logoutTime_ = getDefaultInstance().getLogoutTime();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *登出时间
         * </pre>
         *
         * <code>string logoutTime = 1;</code>
         * @param value The bytes for logoutTime to set.
         * @return This builder for chaining.
         */
        public Builder setLogoutTimeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          logoutTime_ = value;
          onChanged();
          return this;
        }

        private Object loginoutNumber_ = "";
        /**
         * <pre>
         *登出流水号
         * </pre>
         *
         * <code>string loginoutNumber = 2;</code>
         * @return The loginoutNumber.
         */
        public String getLoginoutNumber() {
          Object ref = loginoutNumber_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            loginoutNumber_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         *登出流水号
         * </pre>
         *
         * <code>string loginoutNumber = 2;</code>
         * @return The bytes for loginoutNumber.
         */
        public com.google.protobuf.ByteString
            getLoginoutNumberBytes() {
          Object ref = loginoutNumber_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            loginoutNumber_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *登出流水号
         * </pre>
         *
         * <code>string loginoutNumber = 2;</code>
         * @param value The loginoutNumber to set.
         * @return This builder for chaining.
         */
        public Builder setLoginoutNumber(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          loginoutNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *登出流水号
         * </pre>
         *
         * <code>string loginoutNumber = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearLoginoutNumber() {

          loginoutNumber_ = getDefaultInstance().getLoginoutNumber();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *登出流水号
         * </pre>
         *
         * <code>string loginoutNumber = 2;</code>
         * @param value The bytes for loginoutNumber to set.
         * @return This builder for chaining.
         */
        public Builder setLoginoutNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          loginoutNumber_ = value;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Unit.Logout)
      }

      // @@protoc_insertion_point(class_scope:Unit.Logout)
      private static final Logout DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Logout();
      }

      public static Logout getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Logout>
          PARSER = new com.google.protobuf.AbstractParser<Logout>() {
        @Override
        public Logout parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Logout(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Logout> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Logout> getParserForType() {
        return PARSER;
      }

      @Override
      public Logout getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int LOGOUT_FIELD_NUMBER = 1;
    private Logout logout_;
    /**
     * <code>.Unit.Logout logout = 1;</code>
     * @return Whether the logout field is set.
     */
    @Override
    public boolean hasLogout() {
      return logout_ != null;
    }
    /**
     * <code>.Unit.Logout logout = 1;</code>
     * @return The logout.
     */
    @Override
    public Logout getLogout() {
      return logout_ == null ? Logout.getDefaultInstance() : logout_;
    }
    /**
     * <code>.Unit.Logout logout = 1;</code>
     */
    @Override
    public LogoutOrBuilder getLogoutOrBuilder() {
      return getLogout();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (logout_ != null) {
        output.writeMessage(1, getLogout());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (logout_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLogout());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Unit)) {
        return super.equals(obj);
      }
      Unit other = (Unit) obj;

      if (hasLogout() != other.hasLogout()) return false;
      if (hasLogout()) {
        if (!getLogout()
            .equals(other.getLogout())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLogout()) {
        hash = (37 * hash) + LOGOUT_FIELD_NUMBER;
        hash = (53 * hash) + getLogout().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Unit parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Unit parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Unit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Unit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Unit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Unit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Unit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Unit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Unit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Unit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Unit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Unit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Unit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Unit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Unit)
        UnitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlatformLogout.internal_static_Unit_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlatformLogout.internal_static_Unit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Unit.class, Builder.class);
      }

      // Construct using PlatformLogout.Unit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (logoutBuilder_ == null) {
          logout_ = null;
        } else {
          logout_ = null;
          logoutBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlatformLogout.internal_static_Unit_descriptor;
      }

      @Override
      public Unit getDefaultInstanceForType() {
        return Unit.getDefaultInstance();
      }

      @Override
      public Unit build() {
        Unit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Unit buildPartial() {
        Unit result = new Unit(this);
        if (logoutBuilder_ == null) {
          result.logout_ = logout_;
        } else {
          result.logout_ = logoutBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Unit) {
          return mergeFrom((Unit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Unit other) {
        if (other == Unit.getDefaultInstance()) return this;
        if (other.hasLogout()) {
          mergeLogout(other.getLogout());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Unit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Unit) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Logout logout_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Logout, Logout.Builder, LogoutOrBuilder> logoutBuilder_;
      /**
       * <code>.Unit.Logout logout = 1;</code>
       * @return Whether the logout field is set.
       */
      public boolean hasLogout() {
        return logoutBuilder_ != null || logout_ != null;
      }
      /**
       * <code>.Unit.Logout logout = 1;</code>
       * @return The logout.
       */
      public Logout getLogout() {
        if (logoutBuilder_ == null) {
          return logout_ == null ? Logout.getDefaultInstance() : logout_;
        } else {
          return logoutBuilder_.getMessage();
        }
      }
      /**
       * <code>.Unit.Logout logout = 1;</code>
       */
      public Builder setLogout(Logout value) {
        if (logoutBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          logout_ = value;
          onChanged();
        } else {
          logoutBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Unit.Logout logout = 1;</code>
       */
      public Builder setLogout(
          Logout.Builder builderForValue) {
        if (logoutBuilder_ == null) {
          logout_ = builderForValue.build();
          onChanged();
        } else {
          logoutBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Unit.Logout logout = 1;</code>
       */
      public Builder mergeLogout(Logout value) {
        if (logoutBuilder_ == null) {
          if (logout_ != null) {
            logout_ =
              Logout.newBuilder(logout_).mergeFrom(value).buildPartial();
          } else {
            logout_ = value;
          }
          onChanged();
        } else {
          logoutBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Unit.Logout logout = 1;</code>
       */
      public Builder clearLogout() {
        if (logoutBuilder_ == null) {
          logout_ = null;
          onChanged();
        } else {
          logout_ = null;
          logoutBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Unit.Logout logout = 1;</code>
       */
      public Logout.Builder getLogoutBuilder() {

        onChanged();
        return getLogoutFieldBuilder().getBuilder();
      }
      /**
       * <code>.Unit.Logout logout = 1;</code>
       */
      public LogoutOrBuilder getLogoutOrBuilder() {
        if (logoutBuilder_ != null) {
          return logoutBuilder_.getMessageOrBuilder();
        } else {
          return logout_ == null ?
              Logout.getDefaultInstance() : logout_;
        }
      }
      /**
       * <code>.Unit.Logout logout = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Logout, Logout.Builder, LogoutOrBuilder>
          getLogoutFieldBuilder() {
        if (logoutBuilder_ == null) {
          logoutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Logout, Logout.Builder, LogoutOrBuilder>(
                  getLogout(),
                  getParentForChildren(),
                  isClean());
          logout_ = null;
        }
        return logoutBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Unit)
    }

    // @@protoc_insertion_point(class_scope:Unit)
    private static final Unit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Unit();
    }

    public static Unit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Unit>
        PARSER = new com.google.protobuf.AbstractParser<Unit>() {
      @Override
      public Unit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Unit(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Unit> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Unit> getParserForType() {
      return PARSER;
    }

    @Override
    public Unit getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Unit_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Unit_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Unit_Logout_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Unit_Logout_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024PlatformLogout.proto\"Z\n\004Unit\022\034\n\006logout" +
      "\030\001 \001(\0132\014.Unit.Logout\0324\n\006Logout\022\022\n\nlogout" +
      "Time\030\001 \001(\t\022\026\n\016loginoutNumber\030\002 \001(\tb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Unit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Unit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Unit_descriptor,
        new String[] { "Logout", });
    internal_static_Unit_Logout_descriptor =
      internal_static_Unit_descriptor.getNestedTypes().get(0);
    internal_static_Unit_Logout_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Unit_Logout_descriptor,
        new String[] { "LogoutTime", "LoginoutNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
