package com.tapdata.processor.dataflow.pb.ca;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VehicleLogin.proto

public final class VehicleLogin {
	private VehicleLogin() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
				(com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface UnitOrBuilder extends
			// @@protoc_insertion_point(interface_extends:Unit)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>.Unit.Login login = 1;</code>
		 *
		 * @return Whether the login field is set.
		 */
		boolean hasLogin();

		/**
		 * <code>.Unit.Login login = 1;</code>
		 *
		 * @return The login.
		 */
		Unit.Login getLogin();

		/**
		 * <code>.Unit.Login login = 1;</code>
		 */
		Unit.LoginOrBuilder getLoginOrBuilder();
	}

	/**
	 * Protobuf type {@code Unit}
	 */
	public static final class Unit extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:Unit)
			UnitOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use Unit.newBuilder() to construct.
		private Unit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Unit() {
		}

		@Override
		@SuppressWarnings({"unused"})
		protected Object newInstance(
				UnusedPrivateParameter unused) {
			return new Unit();
		}

		@Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private Unit(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new NullPointerException();
			}
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							Login.Builder subBuilder = null;
							if (login_ != null) {
								subBuilder = login_.toBuilder();
							}
							login_ = input.readMessage(Login.parser(), extensionRegistry);
							if (subBuilder != null) {
								subBuilder.mergeFrom(login_);
								login_ = subBuilder.buildPartial();
							}

							break;
						}
						default: {
							if (!parseUnknownField(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return VehicleLogin.internal_static_Unit_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return VehicleLogin.internal_static_Unit_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							Unit.class, Builder.class);
		}

		public interface LoginOrBuilder extends
				// @@protoc_insertion_point(interface_extends:Unit.Login)
				com.google.protobuf.MessageOrBuilder {

			/**
			 * <pre>
			 * 车辆登入时间
			 * </pre>
			 *
			 * <code>string loginTime = 1;</code>
			 *
			 * @return The loginTime.
			 */
			String getLoginTime();

			/**
			 * <pre>
			 * 车辆登入时间
			 * </pre>
			 *
			 * <code>string loginTime = 1;</code>
			 *
			 * @return The bytes for loginTime.
			 */
			com.google.protobuf.ByteString
			getLoginTimeBytes();

			/**
			 * <pre>
			 * 登入流水号(车载终端每登入一次，登入流水号自动加1，从1开始循环累加，最大值为65535，循环周期为天)
			 * </pre>
			 *
			 * <code>string loginSerialNumber = 2;</code>
			 *
			 * @return The loginSerialNumber.
			 */
			String getLoginSerialNumber();

			/**
			 * <pre>
			 * 登入流水号(车载终端每登入一次，登入流水号自动加1，从1开始循环累加，最大值为65535，循环周期为天)
			 * </pre>
			 *
			 * <code>string loginSerialNumber = 2;</code>
			 *
			 * @return The bytes for loginSerialNumber.
			 */
			com.google.protobuf.ByteString
			getLoginSerialNumberBytes();

			/**
			 * <pre>
			 * ICCID
			 * </pre>
			 *
			 * <code>string iccid = 3;</code>
			 *
			 * @return The iccid.
			 */
			String getIccid();

			/**
			 * <pre>
			 * ICCID
			 * </pre>
			 *
			 * <code>string iccid = 3;</code>
			 *
			 * @return The bytes for iccid.
			 */
			com.google.protobuf.ByteString
			getIccidBytes();
		}

		/**
		 * Protobuf type {@code Unit.Login}
		 */
		public static final class Login extends
				com.google.protobuf.GeneratedMessageV3 implements
				// @@protoc_insertion_point(message_implements:Unit.Login)
				LoginOrBuilder {
			private static final long serialVersionUID = 0L;

			// Use Login.newBuilder() to construct.
			private Login(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
				super(builder);
			}

			private Login() {
				loginTime_ = "";
				loginSerialNumber_ = "";
				iccid_ = "";
			}

			@Override
			@SuppressWarnings({"unused"})
			protected Object newInstance(
					UnusedPrivateParameter unused) {
				return new Login();
			}

			@Override
			public final com.google.protobuf.UnknownFieldSet
			getUnknownFields() {
				return this.unknownFields;
			}

			private Login(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				this();
				if (extensionRegistry == null) {
					throw new NullPointerException();
				}
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder();
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
							case 0:
								done = true;
								break;
							case 10: {
								String s = input.readStringRequireUtf8();

								loginTime_ = s;
								break;
							}
							case 18: {
								String s = input.readStringRequireUtf8();

								loginSerialNumber_ = s;
								break;
							}
							case 26: {
								String s = input.readStringRequireUtf8();

								iccid_ = s;
								break;
							}
							default: {
								if (!parseUnknownField(
										input, unknownFields, extensionRegistry, tag)) {
									done = true;
								}
								break;
							}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(
							e).setUnfinishedMessage(this);
				} finally {
					this.unknownFields = unknownFields.build();
					makeExtensionsImmutable();
				}
			}

			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return VehicleLogin.internal_static_Unit_Login_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return VehicleLogin.internal_static_Unit_Login_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								Login.class, Builder.class);
			}

			public static final int LOGINTIME_FIELD_NUMBER = 1;
			private volatile Object loginTime_;

			/**
			 * <pre>
			 * 车辆登入时间
			 * </pre>
			 *
			 * <code>string loginTime = 1;</code>
			 *
			 * @return The loginTime.
			 */
			@Override
			public String getLoginTime() {
				Object ref = loginTime_;
				if (ref instanceof String) {
					return (String) ref;
				} else {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					loginTime_ = s;
					return s;
				}
			}

			/**
			 * <pre>
			 * 车辆登入时间
			 * </pre>
			 *
			 * <code>string loginTime = 1;</code>
			 *
			 * @return The bytes for loginTime.
			 */
			@Override
			public com.google.protobuf.ByteString
			getLoginTimeBytes() {
				Object ref = loginTime_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					loginTime_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			public static final int LOGINSERIALNUMBER_FIELD_NUMBER = 2;
			private volatile Object loginSerialNumber_;

			/**
			 * <pre>
			 * 登入流水号(车载终端每登入一次，登入流水号自动加1，从1开始循环累加，最大值为65535，循环周期为天)
			 * </pre>
			 *
			 * <code>string loginSerialNumber = 2;</code>
			 *
			 * @return The loginSerialNumber.
			 */
			@Override
			public String getLoginSerialNumber() {
				Object ref = loginSerialNumber_;
				if (ref instanceof String) {
					return (String) ref;
				} else {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					loginSerialNumber_ = s;
					return s;
				}
			}

			/**
			 * <pre>
			 * 登入流水号(车载终端每登入一次，登入流水号自动加1，从1开始循环累加，最大值为65535，循环周期为天)
			 * </pre>
			 *
			 * <code>string loginSerialNumber = 2;</code>
			 *
			 * @return The bytes for loginSerialNumber.
			 */
			@Override
			public com.google.protobuf.ByteString
			getLoginSerialNumberBytes() {
				Object ref = loginSerialNumber_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					loginSerialNumber_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			public static final int ICCID_FIELD_NUMBER = 3;
			private volatile Object iccid_;

			/**
			 * <pre>
			 * ICCID
			 * </pre>
			 *
			 * <code>string iccid = 3;</code>
			 *
			 * @return The iccid.
			 */
			@Override
			public String getIccid() {
				Object ref = iccid_;
				if (ref instanceof String) {
					return (String) ref;
				} else {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					iccid_ = s;
					return s;
				}
			}

			/**
			 * <pre>
			 * ICCID
			 * </pre>
			 *
			 * <code>string iccid = 3;</code>
			 *
			 * @return The bytes for iccid.
			 */
			@Override
			public com.google.protobuf.ByteString
			getIccidBytes() {
				Object ref = iccid_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					iccid_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			private byte memoizedIsInitialized = -1;

			@Override
			public final boolean isInitialized() {
				byte isInitialized = memoizedIsInitialized;
				if (isInitialized == 1) return true;
				if (isInitialized == 0) return false;

				memoizedIsInitialized = 1;
				return true;
			}

			@Override
			public void writeTo(com.google.protobuf.CodedOutputStream output)
					throws java.io.IOException {
				if (!getLoginTimeBytes().isEmpty()) {
					com.google.protobuf.GeneratedMessageV3.writeString(output, 1, loginTime_);
				}
				if (!getLoginSerialNumberBytes().isEmpty()) {
					com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loginSerialNumber_);
				}
				if (!getIccidBytes().isEmpty()) {
					com.google.protobuf.GeneratedMessageV3.writeString(output, 3, iccid_);
				}
				unknownFields.writeTo(output);
			}

			@Override
			public int getSerializedSize() {
				int size = memoizedSize;
				if (size != -1) return size;

				size = 0;
				if (!getLoginTimeBytes().isEmpty()) {
					size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, loginTime_);
				}
				if (!getLoginSerialNumberBytes().isEmpty()) {
					size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loginSerialNumber_);
				}
				if (!getIccidBytes().isEmpty()) {
					size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, iccid_);
				}
				size += unknownFields.getSerializedSize();
				memoizedSize = size;
				return size;
			}

			@Override
			public boolean equals(final Object obj) {
				if (obj == this) {
					return true;
				}
				if (!(obj instanceof Login)) {
					return super.equals(obj);
				}
				Login other = (Login) obj;

				if (!getLoginTime()
						.equals(other.getLoginTime())) return false;
				if (!getLoginSerialNumber()
						.equals(other.getLoginSerialNumber())) return false;
				if (!getIccid()
						.equals(other.getIccid())) return false;
				if (!unknownFields.equals(other.unknownFields)) return false;
				return true;
			}

			@Override
			public int hashCode() {
				if (memoizedHashCode != 0) {
					return memoizedHashCode;
				}
				int hash = 41;
				hash = (19 * hash) + getDescriptor().hashCode();
				hash = (37 * hash) + LOGINTIME_FIELD_NUMBER;
				hash = (53 * hash) + getLoginTime().hashCode();
				hash = (37 * hash) + LOGINSERIALNUMBER_FIELD_NUMBER;
				hash = (53 * hash) + getLoginSerialNumber().hashCode();
				hash = (37 * hash) + ICCID_FIELD_NUMBER;
				hash = (53 * hash) + getIccid().hashCode();
				hash = (29 * hash) + unknownFields.hashCode();
				memoizedHashCode = hash;
				return hash;
			}

			public static Login parseFrom(
					java.nio.ByteBuffer data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static Login parseFrom(
					java.nio.ByteBuffer data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static Login parseFrom(
					com.google.protobuf.ByteString data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static Login parseFrom(
					com.google.protobuf.ByteString data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static Login parseFrom(byte[] data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static Login parseFrom(
					byte[] data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static Login parseFrom(java.io.InputStream input)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input);
			}

			public static Login parseFrom(
					java.io.InputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input, extensionRegistry);
			}

			public static Login parseDelimitedFrom(java.io.InputStream input)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseDelimitedWithIOException(PARSER, input);
			}

			public static Login parseDelimitedFrom(
					java.io.InputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
			}

			public static Login parseFrom(
					com.google.protobuf.CodedInputStream input)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input);
			}

			public static Login parseFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3
						.parseWithIOException(PARSER, input, extensionRegistry);
			}

			@Override
			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder() {
				return DEFAULT_INSTANCE.toBuilder();
			}

			public static Builder newBuilder(Login prototype) {
				return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
			}

			@Override
			public Builder toBuilder() {
				return this == DEFAULT_INSTANCE
						? new Builder() : new Builder().mergeFrom(this);
			}

			@Override
			protected Builder newBuilderForType(
					com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				Builder builder = new Builder(parent);
				return builder;
			}

			/**
			 * Protobuf type {@code Unit.Login}
			 */
			public static final class Builder extends
					com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
					// @@protoc_insertion_point(builder_implements:Unit.Login)
					LoginOrBuilder {
				public static final com.google.protobuf.Descriptors.Descriptor
				getDescriptor() {
					return VehicleLogin.internal_static_Unit_Login_descriptor;
				}

				@Override
				protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
				internalGetFieldAccessorTable() {
					return VehicleLogin.internal_static_Unit_Login_fieldAccessorTable
							.ensureFieldAccessorsInitialized(
									Login.class, Builder.class);
				}

				// Construct using VehicleLogin.Unit.Login.newBuilder()
				private Builder() {
					maybeForceBuilderInitialization();
				}

				private Builder(
						com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
					super(parent);
					maybeForceBuilderInitialization();
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessageV3
							.alwaysUseFieldBuilders) {
					}
				}

				@Override
				public Builder clear() {
					super.clear();
					loginTime_ = "";

					loginSerialNumber_ = "";

					iccid_ = "";

					return this;
				}

				@Override
				public com.google.protobuf.Descriptors.Descriptor
				getDescriptorForType() {
					return VehicleLogin.internal_static_Unit_Login_descriptor;
				}

				@Override
				public Login getDefaultInstanceForType() {
					return Login.getDefaultInstance();
				}

				@Override
				public Login build() {
					Login result = buildPartial();
					if (!result.isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return result;
				}

				@Override
				public Login buildPartial() {
					Login result = new Login(this);
					result.loginTime_ = loginTime_;
					result.loginSerialNumber_ = loginSerialNumber_;
					result.iccid_ = iccid_;
					onBuilt();
					return result;
				}

				@Override
				public Builder clone() {
					return super.clone();
				}

				@Override
				public Builder setField(
						com.google.protobuf.Descriptors.FieldDescriptor field,
						Object value) {
					return super.setField(field, value);
				}

				@Override
				public Builder clearField(
						com.google.protobuf.Descriptors.FieldDescriptor field) {
					return super.clearField(field);
				}

				@Override
				public Builder clearOneof(
						com.google.protobuf.Descriptors.OneofDescriptor oneof) {
					return super.clearOneof(oneof);
				}

				@Override
				public Builder setRepeatedField(
						com.google.protobuf.Descriptors.FieldDescriptor field,
						int index, Object value) {
					return super.setRepeatedField(field, index, value);
				}

				@Override
				public Builder addRepeatedField(
						com.google.protobuf.Descriptors.FieldDescriptor field,
						Object value) {
					return super.addRepeatedField(field, value);
				}

				@Override
				public Builder mergeFrom(com.google.protobuf.Message other) {
					if (other instanceof Login) {
						return mergeFrom((Login) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(Login other) {
					if (other == Login.getDefaultInstance()) return this;
					if (!other.getLoginTime().isEmpty()) {
						loginTime_ = other.loginTime_;
						onChanged();
					}
					if (!other.getLoginSerialNumber().isEmpty()) {
						loginSerialNumber_ = other.loginSerialNumber_;
						onChanged();
					}
					if (!other.getIccid().isEmpty()) {
						iccid_ = other.iccid_;
						onChanged();
					}
					this.mergeUnknownFields(other.unknownFields);
					onChanged();
					return this;
				}

				@Override
				public final boolean isInitialized() {
					return true;
				}

				@Override
				public Builder mergeFrom(
						com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
					Login parsedMessage = null;
					try {
						parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (Login) e.getUnfinishedMessage();
						throw e.unwrapIOException();
					} finally {
						if (parsedMessage != null) {
							mergeFrom(parsedMessage);
						}
					}
					return this;
				}

				private Object loginTime_ = "";

				/**
				 * <pre>
				 * 车辆登入时间
				 * </pre>
				 *
				 * <code>string loginTime = 1;</code>
				 *
				 * @return The loginTime.
				 */
				public String getLoginTime() {
					Object ref = loginTime_;
					if (!(ref instanceof String)) {
						com.google.protobuf.ByteString bs =
								(com.google.protobuf.ByteString) ref;
						String s = bs.toStringUtf8();
						loginTime_ = s;
						return s;
					} else {
						return (String) ref;
					}
				}

				/**
				 * <pre>
				 * 车辆登入时间
				 * </pre>
				 *
				 * <code>string loginTime = 1;</code>
				 *
				 * @return The bytes for loginTime.
				 */
				public com.google.protobuf.ByteString
				getLoginTimeBytes() {
					Object ref = loginTime_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b =
								com.google.protobuf.ByteString.copyFromUtf8(
										(String) ref);
						loginTime_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <pre>
				 * 车辆登入时间
				 * </pre>
				 *
				 * <code>string loginTime = 1;</code>
				 *
				 * @param value The loginTime to set.
				 * @return This builder for chaining.
				 */
				public Builder setLoginTime(
						String value) {
					if (value == null) {
						throw new NullPointerException();
					}

					loginTime_ = value;
					onChanged();
					return this;
				}

				/**
				 * <pre>
				 * 车辆登入时间
				 * </pre>
				 *
				 * <code>string loginTime = 1;</code>
				 *
				 * @return This builder for chaining.
				 */
				public Builder clearLoginTime() {

					loginTime_ = getDefaultInstance().getLoginTime();
					onChanged();
					return this;
				}

				/**
				 * <pre>
				 * 车辆登入时间
				 * </pre>
				 *
				 * <code>string loginTime = 1;</code>
				 *
				 * @param value The bytes for loginTime to set.
				 * @return This builder for chaining.
				 */
				public Builder setLoginTimeBytes(
						com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					checkByteStringIsUtf8(value);

					loginTime_ = value;
					onChanged();
					return this;
				}

				private Object loginSerialNumber_ = "";

				/**
				 * <pre>
				 * 登入流水号(车载终端每登入一次，登入流水号自动加1，从1开始循环累加，最大值为65535，循环周期为天)
				 * </pre>
				 *
				 * <code>string loginSerialNumber = 2;</code>
				 *
				 * @return The loginSerialNumber.
				 */
				public String getLoginSerialNumber() {
					Object ref = loginSerialNumber_;
					if (!(ref instanceof String)) {
						com.google.protobuf.ByteString bs =
								(com.google.protobuf.ByteString) ref;
						String s = bs.toStringUtf8();
						loginSerialNumber_ = s;
						return s;
					} else {
						return (String) ref;
					}
				}

				/**
				 * <pre>
				 * 登入流水号(车载终端每登入一次，登入流水号自动加1，从1开始循环累加，最大值为65535，循环周期为天)
				 * </pre>
				 *
				 * <code>string loginSerialNumber = 2;</code>
				 *
				 * @return The bytes for loginSerialNumber.
				 */
				public com.google.protobuf.ByteString
				getLoginSerialNumberBytes() {
					Object ref = loginSerialNumber_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b =
								com.google.protobuf.ByteString.copyFromUtf8(
										(String) ref);
						loginSerialNumber_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <pre>
				 * 登入流水号(车载终端每登入一次，登入流水号自动加1，从1开始循环累加，最大值为65535，循环周期为天)
				 * </pre>
				 *
				 * <code>string loginSerialNumber = 2;</code>
				 *
				 * @param value The loginSerialNumber to set.
				 * @return This builder for chaining.
				 */
				public Builder setLoginSerialNumber(
						String value) {
					if (value == null) {
						throw new NullPointerException();
					}

					loginSerialNumber_ = value;
					onChanged();
					return this;
				}

				/**
				 * <pre>
				 * 登入流水号(车载终端每登入一次，登入流水号自动加1，从1开始循环累加，最大值为65535，循环周期为天)
				 * </pre>
				 *
				 * <code>string loginSerialNumber = 2;</code>
				 *
				 * @return This builder for chaining.
				 */
				public Builder clearLoginSerialNumber() {

					loginSerialNumber_ = getDefaultInstance().getLoginSerialNumber();
					onChanged();
					return this;
				}

				/**
				 * <pre>
				 * 登入流水号(车载终端每登入一次，登入流水号自动加1，从1开始循环累加，最大值为65535，循环周期为天)
				 * </pre>
				 *
				 * <code>string loginSerialNumber = 2;</code>
				 *
				 * @param value The bytes for loginSerialNumber to set.
				 * @return This builder for chaining.
				 */
				public Builder setLoginSerialNumberBytes(
						com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					checkByteStringIsUtf8(value);

					loginSerialNumber_ = value;
					onChanged();
					return this;
				}

				private Object iccid_ = "";

				/**
				 * <pre>
				 * ICCID
				 * </pre>
				 *
				 * <code>string iccid = 3;</code>
				 *
				 * @return The iccid.
				 */
				public String getIccid() {
					Object ref = iccid_;
					if (!(ref instanceof String)) {
						com.google.protobuf.ByteString bs =
								(com.google.protobuf.ByteString) ref;
						String s = bs.toStringUtf8();
						iccid_ = s;
						return s;
					} else {
						return (String) ref;
					}
				}

				/**
				 * <pre>
				 * ICCID
				 * </pre>
				 *
				 * <code>string iccid = 3;</code>
				 *
				 * @return The bytes for iccid.
				 */
				public com.google.protobuf.ByteString
				getIccidBytes() {
					Object ref = iccid_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b =
								com.google.protobuf.ByteString.copyFromUtf8(
										(String) ref);
						iccid_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <pre>
				 * ICCID
				 * </pre>
				 *
				 * <code>string iccid = 3;</code>
				 *
				 * @param value The iccid to set.
				 * @return This builder for chaining.
				 */
				public Builder setIccid(
						String value) {
					if (value == null) {
						throw new NullPointerException();
					}

					iccid_ = value;
					onChanged();
					return this;
				}

				/**
				 * <pre>
				 * ICCID
				 * </pre>
				 *
				 * <code>string iccid = 3;</code>
				 *
				 * @return This builder for chaining.
				 */
				public Builder clearIccid() {

					iccid_ = getDefaultInstance().getIccid();
					onChanged();
					return this;
				}

				/**
				 * <pre>
				 * ICCID
				 * </pre>
				 *
				 * <code>string iccid = 3;</code>
				 *
				 * @param value The bytes for iccid to set.
				 * @return This builder for chaining.
				 */
				public Builder setIccidBytes(
						com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					checkByteStringIsUtf8(value);

					iccid_ = value;
					onChanged();
					return this;
				}

				@Override
				public final Builder setUnknownFields(
						final com.google.protobuf.UnknownFieldSet unknownFields) {
					return super.setUnknownFields(unknownFields);
				}

				@Override
				public final Builder mergeUnknownFields(
						final com.google.protobuf.UnknownFieldSet unknownFields) {
					return super.mergeUnknownFields(unknownFields);
				}


				// @@protoc_insertion_point(builder_scope:Unit.Login)
			}

			// @@protoc_insertion_point(class_scope:Unit.Login)
			private static final Login DEFAULT_INSTANCE;

			static {
				DEFAULT_INSTANCE = new Login();
			}

			public static Login getDefaultInstance() {
				return DEFAULT_INSTANCE;
			}

			private static final com.google.protobuf.Parser<Login>
					PARSER = new com.google.protobuf.AbstractParser<Login>() {
				@Override
				public Login parsePartialFrom(
						com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
					return new Login(input, extensionRegistry);
				}
			};

			public static com.google.protobuf.Parser<Login> parser() {
				return PARSER;
			}

			@Override
			public com.google.protobuf.Parser<Login> getParserForType() {
				return PARSER;
			}

			@Override
			public Login getDefaultInstanceForType() {
				return DEFAULT_INSTANCE;
			}

		}

		public static final int LOGIN_FIELD_NUMBER = 1;
		private Login login_;

		/**
		 * <code>.Unit.Login login = 1;</code>
		 *
		 * @return Whether the login field is set.
		 */
		@Override
		public boolean hasLogin() {
			return login_ != null;
		}

		/**
		 * <code>.Unit.Login login = 1;</code>
		 *
		 * @return The login.
		 */
		@Override
		public Login getLogin() {
			return login_ == null ? Login.getDefaultInstance() : login_;
		}

		/**
		 * <code>.Unit.Login login = 1;</code>
		 */
		@Override
		public LoginOrBuilder getLoginOrBuilder() {
			return getLogin();
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (login_ != null) {
				output.writeMessage(1, getLogin());
			}
			unknownFields.writeTo(output);
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) return size;

			size = 0;
			if (login_ != null) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, getLogin());
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Unit)) {
				return super.equals(obj);
			}
			Unit other = (Unit) obj;

			if (hasLogin() != other.hasLogin()) return false;
			if (hasLogin()) {
				if (!getLogin()
						.equals(other.getLogin())) return false;
			}
			if (!unknownFields.equals(other.unknownFields)) return false;
			return true;
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (hasLogin()) {
				hash = (37 * hash) + LOGIN_FIELD_NUMBER;
				hash = (53 * hash) + getLogin().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Unit parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Unit parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Unit parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Unit parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Unit parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Unit parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Unit parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Unit parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Unit parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static Unit parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static Unit parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static Unit parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Unit prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code Unit}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:Unit)
				UnitOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return VehicleLogin.internal_static_Unit_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return VehicleLogin.internal_static_Unit_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								Unit.class, Builder.class);
			}

			// Construct using VehicleLogin.Unit.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				if (loginBuilder_ == null) {
					login_ = null;
				} else {
					login_ = null;
					loginBuilder_ = null;
				}
				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return VehicleLogin.internal_static_Unit_descriptor;
			}

			@Override
			public Unit getDefaultInstanceForType() {
				return Unit.getDefaultInstance();
			}

			@Override
			public Unit build() {
				Unit result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public Unit buildPartial() {
				Unit result = new Unit(this);
				if (loginBuilder_ == null) {
					result.login_ = login_;
				} else {
					result.login_ = loginBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return super.clone();
			}

			@Override
			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return super.setField(field, value);
			}

			@Override
			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@Override
			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Unit) {
					return mergeFrom((Unit) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Unit other) {
				if (other == Unit.getDefaultInstance()) return this;
				if (other.hasLogin()) {
					mergeLogin(other.getLogin());
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				Unit parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Unit) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private Login login_;
			private com.google.protobuf.SingleFieldBuilderV3<
					Login, Login.Builder, LoginOrBuilder> loginBuilder_;

			/**
			 * <code>.Unit.Login login = 1;</code>
			 *
			 * @return Whether the login field is set.
			 */
			public boolean hasLogin() {
				return loginBuilder_ != null || login_ != null;
			}

			/**
			 * <code>.Unit.Login login = 1;</code>
			 *
			 * @return The login.
			 */
			public Login getLogin() {
				if (loginBuilder_ == null) {
					return login_ == null ? Login.getDefaultInstance() : login_;
				} else {
					return loginBuilder_.getMessage();
				}
			}

			/**
			 * <code>.Unit.Login login = 1;</code>
			 */
			public Builder setLogin(Login value) {
				if (loginBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					login_ = value;
					onChanged();
				} else {
					loginBuilder_.setMessage(value);
				}

				return this;
			}

			/**
			 * <code>.Unit.Login login = 1;</code>
			 */
			public Builder setLogin(
					Login.Builder builderForValue) {
				if (loginBuilder_ == null) {
					login_ = builderForValue.build();
					onChanged();
				} else {
					loginBuilder_.setMessage(builderForValue.build());
				}

				return this;
			}

			/**
			 * <code>.Unit.Login login = 1;</code>
			 */
			public Builder mergeLogin(Login value) {
				if (loginBuilder_ == null) {
					if (login_ != null) {
						login_ =
								Login.newBuilder(login_).mergeFrom(value).buildPartial();
					} else {
						login_ = value;
					}
					onChanged();
				} else {
					loginBuilder_.mergeFrom(value);
				}

				return this;
			}

			/**
			 * <code>.Unit.Login login = 1;</code>
			 */
			public Builder clearLogin() {
				if (loginBuilder_ == null) {
					login_ = null;
					onChanged();
				} else {
					login_ = null;
					loginBuilder_ = null;
				}

				return this;
			}

			/**
			 * <code>.Unit.Login login = 1;</code>
			 */
			public Login.Builder getLoginBuilder() {

				onChanged();
				return getLoginFieldBuilder().getBuilder();
			}

			/**
			 * <code>.Unit.Login login = 1;</code>
			 */
			public LoginOrBuilder getLoginOrBuilder() {
				if (loginBuilder_ != null) {
					return loginBuilder_.getMessageOrBuilder();
				} else {
					return login_ == null ?
							Login.getDefaultInstance() : login_;
				}
			}

			/**
			 * <code>.Unit.Login login = 1;</code>
			 */
			private com.google.protobuf.SingleFieldBuilderV3<
					Login, Login.Builder, LoginOrBuilder>
			getLoginFieldBuilder() {
				if (loginBuilder_ == null) {
					loginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
							Login, Login.Builder, LoginOrBuilder>(
							getLogin(),
							getParentForChildren(),
							isClean());
					login_ = null;
				}
				return loginBuilder_;
			}

			@Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}


			// @@protoc_insertion_point(builder_scope:Unit)
		}

		// @@protoc_insertion_point(class_scope:Unit)
		private static final Unit DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new Unit();
		}

		public static Unit getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Unit>
				PARSER = new com.google.protobuf.AbstractParser<Unit>() {
			@Override
			public Unit parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Unit(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<Unit> parser() {
			return PARSER;
		}

		@Override
		public com.google.protobuf.Parser<Unit> getParserForType() {
			return PARSER;
		}

		@Override
		public Unit getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_Unit_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_Unit_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_Unit_Login_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_Unit_Login_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
			descriptor;

	static {
		String[] descriptorData = {
				"\n\022VehicleLogin.proto\"h\n\004Unit\022\032\n\005login\030\001 " +
						"\001(\0132\013.Unit.Login\032D\n\005Login\022\021\n\tloginTime\030\001" +
						" \001(\t\022\031\n\021loginSerialNumber\030\002 \001(\t\022\r\n\005iccid" +
						"\030\003 \001(\tb\006proto3"
		};
		descriptor = com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[]{
						});
		internal_static_Unit_descriptor =
				getDescriptor().getMessageTypes().get(0);
		internal_static_Unit_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_Unit_descriptor,
				new String[]{"Login",});
		internal_static_Unit_Login_descriptor =
				internal_static_Unit_descriptor.getNestedTypes().get(0);
		internal_static_Unit_Login_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_Unit_Login_descriptor,
				new String[]{"LoginTime", "LoginSerialNumber", "Iccid",});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
