package com.tapdata.tm.dql.dto;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Map;

@Data
public class DqlEventDto implements Serializable {
    public static final String FIELD_ID = "_id";
    public static final String FIELD_EVENT_ID = "event_id";
    public static final String FIELD_TASK_ID = "task_id";
    public static final String FIELD_TASK_RECORD_ID = "task_record_id";
    public static final String FIELD_TASK_NAME = "task_name";
    public static final String FIELD_TASK_VERSION = "task_version";
    public static final String FIELD_AGENT_ID = "agent_id";
    public static final String FIELD_SOURCE_NODE_ID = "source_node_id";
    public static final String FIELD_SOURCE_NODE_NAME = "source_node_name";
    public static final String FIELD_TARGET_NODE_ID = "target_node_id";
    public static final String FIELD_TARGET_NODE_NAME = "target_node_name";
    public static final String FIELD_FAILED_NODE_ID = "failed_node_id";
    public static final String FIELD_FAILED_NODE_NAME = "failed_node_name";
    public static final String FIELD_FAILED_STAGE = "failed_stage";
    public static final String FIELD_SOURCE_TABLE = "source_table";
    public static final String FIELD_TARGET_TABLE = "target_table";
    public static final String FIELD_TABLE_ID = "table_id";
    public static final String FIELD_DML_TYPE = "dml_type";
    public static final String FIELD_EVENT_TIME = "event_time";
    public static final String FIELD_CAPTURE_SEQ = "capture_seq";
    public static final String FIELD_FAILED_AT = "failed_at";
    public static final String FIELD_EVENT_KEY = "event_key";
    public static final String FIELD_EVENT_KEY_MISSING = "event_key_missing";
    public static final String FIELD_EVENT_IDENTITY = "event_identity";
    public static final String FIELD_RECORD_IDENTITY = "record_identity";
    public static final String FIELD_RECORD_IDENTITY_TYPE = "record_identity_type";
    public static final String FIELD_RECORD_IDENTITY_FIELDS = "record_identity_fields";
    public static final String FIELD_PAYLOAD_FORMAT = "payload_format";
    public static final String FIELD_PAYLOAD_DATA = "payload_data";
    public static final String FIELD_PAYLOAD_HASH = "payload_hash";
    public static final String FIELD_PAYLOAD_SIZE = "payload_size";
    public static final String FIELD_PAYLOAD_COMPLETE = "payload_complete";
    public static final String FIELD_PAYLOAD_PREVIEW = "payload_preview";
    public static final String FIELD_PAYLOAD_PREVIEW_TRUNCATED = "payload_preview_truncated";
    public static final String FIELD_ERROR_TYPE = "error_type";
    public static final String FIELD_ERROR_CODE = "error_code";
    public static final String FIELD_EXCEPTION_SCOPE = "exception_scope";
    public static final String FIELD_ROUTE_DECISION = "route_decision";
    public static final String FIELD_CLASSIFICATION_REASON = "classification_reason";
    public static final String FIELD_CLASSIFICATION_CONFIDENCE = "classification_confidence";
    public static final String FIELD_ERROR_DETAILS = "error_details";
    public static final String FIELD_ERROR_DETAILS_TRUNCATED = "error_details_truncated";
    public static final String FIELD_RAW_ERROR_REF = "raw_error_ref";
    public static final String FIELD_STATUS = "status";
    public static final String FIELD_RECOVERY_STATUS_BEFORE_SYNC = "recovery_status_before_sync";
    public static final String FIELD_NOT_REPROCESSABLE_REASON = "not_reprocessable_reason";
    public static final String FIELD_RECOVERY_COUNT = "recovery_count";
    public static final String FIELD_LAST_RECOVERY_TIME = "last_recovery_time";
    public static final String FIELD_LAST_RECOVERY_USER_ID = "last_recovery_user_id";
    public static final String FIELD_LAST_RECOVERY_USER_NAME = "last_recovery_user_name";
    public static final String FIELD_LAST_RECOVERY_RESULT = "last_recovery_result";
    public static final String FIELD_CURRENT_BATCH_ID = "current_batch_id";
    public static final String FIELD_OVERWRITE_RISK = "overwrite_risk";
    public static final String FIELD_OVERWRITE_RISK_MESSAGE = "overwrite_risk_message";
    public static final String FIELD_LATER_SUCCESS_AT = "later_success_at";
    public static final String FIELD_LATER_SUCCESS_EVENT_TIME = "later_success_event_time";
    public static final String FIELD_LATER_SUCCESS_CAPTURE_SEQ = "later_success_capture_seq";
    public static final String FIELD_LATER_SUCCESS_DML_TYPE = "later_success_dml_type";
    public static final String FIELD_RECOVERY_ATTEMPTS = "recovery_attempts";
    public static final String FIELD_CREATED = "created";
    public static final String FIELD_UPDATED = "updated";
    public static final String FIELD_TTL_AT = "ttl_at";

    private String id;
    private String eventId;
    private String taskId;
    private String taskRecordId;
    private String taskName;
    private Long taskVersion;
    private String agentId;
    private String sourceNodeId;
    private String sourceNodeName;
    private String targetNodeId;
    private String targetNodeName;
    private String failedNodeId;
    private String failedNodeName;
    private String failedStage;
    private String sourceTable;
    private String targetTable;
    private String tableId;
    private String dmlType;
    private Date eventTime;
    private Long captureSeq;
    private Date failedAt;
    private Map<String, Object> eventKey;
    private Boolean eventKeyMissing;
    private String eventIdentity;
    private String recordIdentity;
    private String recordIdentityType;
    private List<String> recordIdentityFields;
    private String payloadFormat;
    private Object payloadData;
    private String payloadHash;
    private Long payloadSize;
    private Boolean payloadComplete;
    private Map<String, Object> payloadPreview;
    private Boolean payloadPreviewTruncated;
    private String errorType;
    private String errorCode;
    private String exceptionScope;
    private String routeDecision;
    private String classificationReason;
    private String classificationConfidence;
    private String errorDetails;
    private Boolean errorDetailsTruncated;
    private String rawErrorRef;
    private String status;
    private String recoveryStatusBeforeSync;
    private String notReprocessableReason;
    private Integer recoveryCount;
    private Date lastRecoveryTime;
    private String lastRecoveryUserId;
    private String lastRecoveryUserName;
    private String lastRecoveryResult;
    private String currentBatchId;
    private Boolean overwriteRisk;
    private String overwriteRiskMessage;
    private Date laterSuccessAt;
    private Date laterSuccessEventTime;
    private Long laterSuccessCaptureSeq;
    private String laterSuccessDmlType;
    private List<DqlRecoveryAttemptDto> recoveryAttempts;
    private Date created;
    private Date updated;
    private Date ttlAt;
}
