package io.tapdata.modules.api.net.error;

public interface NetErrors {
	int ERROR_ENCODER_NOT_FOUND = 8000;
	int JAVA_CUSTOM_DESERIALIZE_FAILED = 8001;
	int ENCODE_NOT_SUPPORTED = 8002;
	int RESURRECT_DATA_NULL = 8003;
	int ID_TYPE_NOT_FOUND = 8004;
	int GATEWAY_SESSION_HANDLER_CLASS_NEW_FAILED = 8005;
}
