spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/tapdata
      ssl: false
      sslCA: ""
      sslCertKey: ""
      conn_params: ""

# 使用JdkHttpServerConfig jdk 内置的httpserver开启http服务，避免tomcat也暴露端点
management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "prometheus, info"

tapdata:
  monitor:
    enable: true
    EFPort: 3035
  cloud:
    accessCode: <ACCESS_CODE>
    retryTime: 3
    baseURLs:
      http://127.0.0.1:3030/api/
  mode: cluster  #cluster/singleton
